-- 13-6 SYSTEM 계정으로 DBA_접두어 사용하기 (SYSTEM 계정으로 접속했을 때)
SELECT * FROM DBA_TABLES;

-- 15-2 SCOTT 계정으로 사용자 생성하기
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

-- 15-3 SYSTEM 사용자로 접속 후 ORCLSTUDY 사용자에게 권한 부여하기
GRANT CREATE SESSION TO ORCLSTUDY;

-- 사용자 정보 조회
SELECT * FROM ALL_USERS WHERE USERNAME = 'ORCLSTUDY';
SELECT * FROM DBA_USERS WHERE USERNAME = 'ORCLSTUDY'
SELECT * FROM DBA_OBJECTS WHERE OWNER = 'ORCLSTUDY';

-- 15-4 사용자 정보(패스워드) 변경하기
ALTER USER ORCLSTUDY IDENTIFIED BY ORCL;

-- 15-7 SYSTEM 계정으로 접속하여 사용자(ORCLSTUDY) 생성하기
CREATE USER ORCLSTUDY IDENTIFIED BY ORACLE;

-- 15-8 사용자 권한 부여하기
GRANT RESOURCE, CREATE SESSION, CREATE TABLE TO ORCLSTUDY;






